emacs: Rewrite ec wrapper to start Emacs in GUI mode
When starting Emacs in daemon mode, the user config loads prior to
creating the first frame, complicating configuration (for example,
some code segments have to be invoked within
`server-after-make-frame-hook`). To avoid these issues, we opt to
launch Emacs in GUI mode initially, then start an Emacs server within
this process.

diff --git a/emacs/.local/bin/ec b/emacs/.local/bin/ec
--- a/emacs/.local/bin/ec
+++ b/emacs/.local/bin/ec
@@ -1,17 +1,8 @@
 #!/usr/bin/env bash
 # -*- mode: sh; -*-
-# Emacsclient wrapper which opens files in an existing frame if possible.
+# Emacsclient wrapper.
 
-# if no args open new frame
-if [ $# -eq 0 ]; then
-    emacsclient -c -n -a ""
-    exit
-fi
-
-emacsclient -e "(frames-on-display-list \"$DISPLAY\")" &>/dev/null
-
-if [ $? -eq 0 ]; then
-    emacsclient -n "$*"
-else
-    emacsclient -c -n "$*"
-fi
+# Try connecting to an existing server. This may fail if a server is
+# not running or no arguments were provided; in this case, start a new
+# Emacs instance in the background.
+emacsclient -n "$@" &>/dev/null || (emacs "$@" >/dev/null 2>&1 &)
